# Generated by Django 4.1.2 on 2022-10-27 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=10, verbose_name='Ingrese número de cédula')),
                ('nombres', models.CharField(blank=True, max_length=50, verbose_name='Ingrese nombres')),
                ('cargo', models.CharField(blank=True, max_length=50, verbose_name='Ingrese cargo')),
                ('rol', models.CharField(blank=True, max_length=50, verbose_name='Ingrese rol')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='Ingrese estado')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=10, verbose_name='Ingrese número de cédula')),
                ('nombres', models.CharField(blank=True, max_length=50, verbose_name='Ingrese nombres')),
                ('departamento', models.CharField(blank=True, max_length=50, verbose_name='Ingrese departamento')),
                ('cargo', models.CharField(blank=True, max_length=50, verbose_name='Ingrese cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('idSalas', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50, verbose_name='Ingrese nombres')),
                ('ubicacion', models.CharField(blank=True, max_length=50, verbose_name='Ingrese ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva_salas',
            fields=[
                ('idReservas', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Ingrese fecha a reservar')),
                ('horaInicio', models.DateTimeField(verbose_name='Ingrese hora inicio')),
                ('horaFin', models.DateTimeField(verbose_name='Ingrese hora fin')),
                ('estado', models.CharField(blank=True, max_length=10, verbose_name='Ingrese estado')),
                ('motivo', models.CharField(blank=True, max_length=50, verbose_name='Ingrese motivo')),
                ('fk_idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clientes')),
                ('fk_idSalas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.salas')),
            ],
        ),
    ]
