# Generated by Django 4.1.2 on 2022-10-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_administrador_estado2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='estado2',
        ),
    ]
