# Generated by Django 4.1.2 on 2022-10-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_administrador_estado2'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ingrese usuario'),
        ),
    ]
