# Generated by Django 4.1.2 on 2022-10-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_administrador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='password',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ingrese contraseña'),
        ),
    ]
